const CON = {
  REGISTRATION_START: 'REGISTRATION_START',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILURE: 'REGISTRATION_FAILURE',
  SET_USER_DATA: 'SET_USER_DATA',
  ADD_BLOCK: 'ADD_BLOCK',
  ADD_LINK: 'ADD_LINK',
}

export default CON
